[project]
name = "beholder"
version = "0.1.0"
description = "Live plotting for multiprocessing data streams"
readme = "README.md"
authors = [
    { name = "mateusglucas" },
]
requires-python = ">=3.12"
dependencies = [
    "pyqtgraph>=0.14.0",
    "pyside6>=6.11.1",
]

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"
